//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Cooler {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cooler.ICooler")]
    public interface ICooler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICooler/CalculateCoolnes", ReplyAction="http://tempuri.org/ICooler/CalculateCoolnesResponse")]
        bool CalculateCoolnes(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICooler/CalculateCoolnes", ReplyAction="http://tempuri.org/ICooler/CalculateCoolnesResponse")]
        System.Threading.Tasks.Task<bool> CalculateCoolnesAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoolerChannel : WebClient.Cooler.ICooler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoolerClient : System.ServiceModel.ClientBase<WebClient.Cooler.ICooler>, WebClient.Cooler.ICooler {
        
        public CoolerClient() {
        }
        
        public CoolerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoolerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoolerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoolerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CalculateCoolnes(string name) {
            return base.Channel.CalculateCoolnes(name);
        }
        
        public System.Threading.Tasks.Task<bool> CalculateCoolnesAsync(string name) {
            return base.Channel.CalculateCoolnesAsync(name);
        }
    }
}
